title: WADTFY
description: WADTFY Docs
theme: just-the-docs

url: https://pages.atc-github.azure.cloud.bmw/WADTFY/wadtfy-docs/

aux_links:
  Int: https://argocd.api-i.bmwgroup.net
  Prod: https://argocd.api.bmwgroup.net

color_scheme: unity

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"


enable_copy_code_button: true
